# Generated by Django 2.1.7 on 2019-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='ficollid',
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='fimd',
            field=models.IntegerField(),
        ),
    ]
