# Generated by Django 2.1.7 on 2019-04-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190405_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collegeid', models.CharField(max_length=30, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctors')),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.logins')),
            ],
        ),
    ]
