# Generated by Django 2.1.7 on 2019-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='question',
            name='Collegeid',
            field=models.CharField(max_length=30),
        ),
    ]
