# Generated by Django 2.1.7 on 2019-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190409_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Department',
            field=models.CharField(default='mca', max_length=50),
        ),
    ]
