# Generated by Django 2.1.7 on 2019-04-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_register_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnosis', models.TextField()),
                ('clinicalhistory', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='Department',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='case_history',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Register'),
        ),
        migrations.AddField(
            model_name='case_history',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.logins'),
        ),
    ]
