# Generated by Django 2.1.7 on 2019-04-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190424_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_history',
            name='ids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.doctors'),
            preserve_default=False,
        ),
    ]
