# Generated by Django 2.1.7 on 2019-04-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='response',
        ),
    ]
