# Generated by Django 2.1.7 on 2019-04-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_delete_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_response', models.TextField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.question')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Register')),
            ],
        ),
    ]
