# Generated by Django 2.1.7 on 2019-04-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_doctor_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_response',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.logins'),
        ),
    ]
