# Generated by Django 2.1.7 on 2019-04-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_request_appoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_appoints',
            name='ids',
        ),
        migrations.DeleteModel(
            name='request_appoints',
        ),
    ]
