# Generated by Django 2.1.7 on 2019-04-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_request_appoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_appoints',
            name='ids',
        ),
        migrations.DeleteModel(
            name='request_appoints',
        ),
    ]
