# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_student_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegid', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('question', models.TextField()),
            ],
        ),
    ]
