# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_approved_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_questions',
            name='doctor_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
