# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_approved_questions_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_questions',
            name='doctor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
