# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_approved_questions_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_from_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Approved_questions')),
            ],
        ),
    ]
